"""
MCP Tool Catalog -- the canonical source of truth for every tool the MCP
Gateway is allowed to expose.

This module is imported by BOTH the standalone MCP server (mcp_server/server.py)
AND the backend's Tool Registry seeder (scripts/seed_database.py), so the
metadata the LLM planner sees, the metadata stored in Postgres, and the
metadata enforced at execution time can never drift apart.

IMPORTANT: this list is intentionally never handed to the LLM in full. The
backend's ToolRetrievalEngine (app/routing/tool_retrieval.py) is the only
component allowed to narrow it down to a small candidate set per request.
"""
from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class ToolMetadata:
    name: str
    description: str
    category: str  # network | database | server | security | logging | knowledge
    risk_level: str  # LOW | MEDIUM | HIGH | CRITICAL
    requires_approval: bool
    required_roles: list[str]
    input_schema: dict[str, Any]
    output_schema: dict[str, Any]
    timeout: int = 30


TOOL_CATALOG: list[ToolMetadata] = [
    # ---------------------------------------------------------------- LOW risk
    ToolMetadata(
        name="ping_device",
        description="Send ICMP ping to a network device or host and measure round-trip latency and packet loss.",
        category="network",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "Network Engineer", "System Administrator",
                         "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"target": {"type": "string"}}, "required": ["target"]},
        output_schema={"type": "object", "properties": {"reachable": {"type": "boolean"},
                                                          "latency_ms": {"type": "number"},
                                                          "packet_loss_pct": {"type": "number"}}},
        timeout=10,
    ),
    ToolMetadata(
        name="check_dns",
        description="Resolve a hostname and verify DNS record correctness and resolver response time.",
        category="network",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "Network Engineer", "System Administrator",
                         "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object", "properties": {"resolved": {"type": "boolean"},
                                                          "records": {"type": "array"}, "resolve_time_ms": {"type": "number"}}},
        timeout=10,
    ),
    ToolMetadata(
        name="check_http",
        description="Perform an HTTP(S) request against a website/endpoint and report status code, response time, and TLS info.",
        category="network",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "Network Engineer", "System Administrator",
                         "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"url": {"type": "string"}}, "required": ["url"]},
        output_schema={"type": "object", "properties": {"status_code": {"type": "integer"},
                                                          "response_time_s": {"type": "number"}}},
        timeout=15,
    ),
    ToolMetadata(
        name="check_server",
        description="Check whether a server host is up and report basic reachability and uptime.",
        category="server",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object", "properties": {"status": {"type": "string"}, "uptime_days": {"type": "number"}}},
        timeout=15,
    ),
    ToolMetadata(
        name="check_server_status",
        description="Report aggregated health status (CPU, memory, disk, service state) of a server.",
        category="server",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object", "properties": {"status": {"type": "string"}}},
        timeout=15,
    ),
    ToolMetadata(
        name="check_ssl",
        description="Inspect a TLS/SSL certificate for expiry, chain validity, and issuer information.",
        category="security",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "Security Analyst", "System Administrator",
                         "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object", "properties": {"valid": {"type": "boolean"}, "days_until_expiry": {"type": "integer"}}},
        timeout=15,
    ),
    ToolMetadata(
        name="check_certificate",
        description="Validate a certificate file/chain against the expected domain and CA trust store.",
        category="security",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "Security Analyst", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object", "properties": {"trusted": {"type": "boolean"}}},
        timeout=15,
    ),
    ToolMetadata(
        name="check_port",
        description="Check whether a TCP/UDP port is open, closed, or filtered on a given host.",
        category="network",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "Network Engineer", "System Administrator",
                         "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}, "port": {"type": "integer"}},
                      "required": ["hostname", "port"]},
        output_schema={"type": "object", "properties": {"open": {"type": "boolean"}}},
        timeout=10,
    ),
    ToolMetadata(
        name="check_service",
        description="Check whether a named OS service/process is running on a server.",
        category="server",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}, "service_name": {"type": "string"}},
                      "required": ["hostname", "service_name"]},
        output_schema={"type": "object", "properties": {"running": {"type": "boolean"}}},
        timeout=15,
    ),
    ToolMetadata(
        name="check_database",
        description="Check database connectivity and overall health status (read-only health probe).",
        category="database",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "Database Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"database_name": {"type": "string"}}, "required": ["database_name"]},
        output_schema={"type": "object", "properties": {"status": {"type": "string"}, "connections": {"type": "integer"}}},
        timeout=15,
    ),
    ToolMetadata(
        name="get_system_metrics",
        description="Retrieve a snapshot of general system metrics (CPU, memory, disk, network) for a host.",
        category="server",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object"},
        timeout=15,
    ),
    ToolMetadata(
        name="get_cpu_usage",
        description="Retrieve current CPU utilization percentage for a server.",
        category="server",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object", "properties": {"cpu_usage_pct": {"type": "number"}}},
        timeout=10,
    ),
    ToolMetadata(
        name="get_memory_usage",
        description="Retrieve current memory (RAM) utilization for a server.",
        category="server",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object", "properties": {"memory_usage_pct": {"type": "number"}}},
        timeout=10,
    ),
    ToolMetadata(
        name="get_disk_usage",
        description="Retrieve current disk utilization for a server or volume.",
        category="server",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object", "properties": {"disk_usage_pct": {"type": "number"}}},
        timeout=10,
    ),
    ToolMetadata(
        name="get_network_latency",
        description="Measure network latency between two points in the infrastructure.",
        category="network",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "Network Engineer", "System Administrator",
                         "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"source": {"type": "string"}, "destination": {"type": "string"}},
                      "required": ["destination"]},
        output_schema={"type": "object", "properties": {"latency_ms": {"type": "number"}}},
        timeout=10,
    ),
    ToolMetadata(
        name="get_process_status",
        description="Retrieve the status and resource consumption of a specific OS process.",
        category="server",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}, "process_name": {"type": "string"}},
                      "required": ["hostname", "process_name"]},
        output_schema={"type": "object", "properties": {"running": {"type": "boolean"}}},
        timeout=10,
    ),
    # ------------------------------------------------------------- MEDIUM risk
    ToolMetadata(
        name="search_logs",
        description="Search application/system logs for a service within a time range and keyword/pattern.",
        category="logging",
        risk_level="MEDIUM",
        requires_approval=False,
        required_roles=["IT Support", "Network Engineer", "Database Administrator", "Security Analyst",
                         "System Administrator", "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"service": {"type": "string"}, "query": {"type": "string"},
                                                         "time_range_minutes": {"type": "integer"}},
                      "required": ["service"]},
        output_schema={"type": "object", "properties": {"matches": {"type": "array"}}},
        timeout=30,
    ),
    ToolMetadata(
        name="query_incident_history",
        description="Query historical incidents matching a service, symptom, or keyword for pattern matching.",
        category="knowledge",
        risk_level="MEDIUM",
        requires_approval=False,
        required_roles=["IT Support", "Network Engineer", "Database Administrator", "Security Analyst",
                         "System Administrator", "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]},
        output_schema={"type": "object", "properties": {"incidents": {"type": "array"}}},
        timeout=15,
    ),
    ToolMetadata(
        name="query_database_readonly",
        description="Execute a read-only, pre-validated query against a database for diagnostic purposes.",
        category="database",
        risk_level="MEDIUM",
        requires_approval=False,
        required_roles=["Database Administrator", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"database_name": {"type": "string"}, "query_id": {"type": "string"}},
                      "required": ["database_name", "query_id"]},
        output_schema={"type": "object", "properties": {"rows": {"type": "array"}}},
        timeout=30,
    ),
    ToolMetadata(
        name="get_database_metrics",
        description="Retrieve database performance metrics: connection pool usage, query latency, replication lag.",
        category="database",
        risk_level="MEDIUM",
        requires_approval=False,
        required_roles=["Database Administrator", "System Administrator", "Infrastructure Administrator",
                         "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"database_name": {"type": "string"}}, "required": ["database_name"]},
        output_schema={"type": "object"},
        timeout=15,
    ),
    ToolMetadata(
        name="search_sop",
        description="Semantic search over Standard Operating Procedures and troubleshooting documentation.",
        category="knowledge",
        risk_level="LOW",
        requires_approval=False,
        required_roles=["Viewer", "IT Support", "Network Engineer", "Database Administrator", "Security Analyst",
                         "System Administrator", "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]},
        output_schema={"type": "object", "properties": {"documents": {"type": "array"}}},
        timeout=15,
    ),
    # --------------------------------------------------------------- HIGH risk
    ToolMetadata(
        name="restart_service",
        description="Restart a named OS service on a server. Causes a brief service interruption.",
        category="server",
        risk_level="HIGH",
        requires_approval=True,
        required_roles=["System Administrator", "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}, "service_name": {"type": "string"}},
                      "required": ["hostname", "service_name"]},
        output_schema={"type": "object", "properties": {"restarted": {"type": "boolean"}}},
        timeout=30,
    ),
    ToolMetadata(
        name="restart_database",
        description="Restart a database instance. Causes service interruption for all connected applications.",
        category="database",
        risk_level="HIGH",
        requires_approval=True,
        required_roles=["Database Administrator", "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"database_name": {"type": "string"}}, "required": ["database_name"]},
        output_schema={"type": "object", "properties": {"restarted": {"type": "boolean"}}},
        timeout=60,
    ),
    ToolMetadata(
        name="clear_cache",
        description="Clear application or CDN cache. May cause a temporary spike in origin load.",
        category="server",
        risk_level="HIGH",
        requires_approval=True,
        required_roles=["System Administrator", "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"target": {"type": "string"}}, "required": ["target"]},
        output_schema={"type": "object", "properties": {"cleared": {"type": "boolean"}}},
        timeout=30,
    ),
    ToolMetadata(
        name="modify_configuration",
        description="Modify a service or infrastructure configuration file/parameter. Requires change control.",
        category="server",
        risk_level="HIGH",
        requires_approval=True,
        required_roles=["System Administrator", "Infrastructure Administrator", "Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"target": {"type": "string"}, "change": {"type": "string"}},
                      "required": ["target", "change"]},
        output_schema={"type": "object", "properties": {"applied": {"type": "boolean"}}},
        timeout=30,
    ),
    # ----------------------------------------------------------- CRITICAL risk
    ToolMetadata(
        name="delete_database",
        description="Permanently delete a database instance and all its data. Irreversible.",
        category="database",
        risk_level="CRITICAL",
        requires_approval=True,
        required_roles=["Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"database_name": {"type": "string"}}, "required": ["database_name"]},
        output_schema={"type": "object", "properties": {"deleted": {"type": "boolean"}}},
        timeout=60,
    ),
    ToolMetadata(
        name="shutdown_server",
        description="Power off a server. All services on the server become unavailable.",
        category="server",
        risk_level="CRITICAL",
        requires_approval=True,
        required_roles=["Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"hostname": {"type": "string"}}, "required": ["hostname"]},
        output_schema={"type": "object", "properties": {"shutdown": {"type": "boolean"}}},
        timeout=60,
    ),
    ToolMetadata(
        name="modify_firewall",
        description="Modify firewall rules affecting network traffic to/from production infrastructure.",
        category="security",
        risk_level="CRITICAL",
        requires_approval=True,
        required_roles=["Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"rule": {"type": "string"}}, "required": ["rule"]},
        output_schema={"type": "object", "properties": {"applied": {"type": "boolean"}}},
        timeout=30,
    ),
    ToolMetadata(
        name="delete_production_data",
        description="Permanently delete production data records. Irreversible and highly destructive.",
        category="database",
        risk_level="CRITICAL",
        requires_approval=True,
        required_roles=["Enterprise Administrator"],
        input_schema={"type": "object", "properties": {"target": {"type": "string"}}, "required": ["target"]},
        output_schema={"type": "object", "properties": {"deleted": {"type": "boolean"}}},
        timeout=60,
    ),
]


def get_tool(name: str) -> ToolMetadata | None:
    return next((t for t in TOOL_CATALOG if t.name == name), None)


def all_tool_names() -> list[str]:
    return [t.name for t in TOOL_CATALOG]
